[package]
name = "kpdf-icon-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
icns = "0.3.1"
image = { version = "0.25.9", default-features = false, features = ["png", "ico"] }
